services:
  gateway-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_microservice
    restart: always
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    env_file:
      - .env

networks:
  default:
    name: microservices_net
    external: true

      

      