require('dotenv').config();
const express=require('express'); const cors=require('cors'); const mongoose=require('mongoose');
const app=express(); const PORT=process.env.PORT||8002; const DB_URL=process.env.DB_URL;
const Product=mongoose.model('Product', new mongoose.Schema({name:{type:String,required:true},desc:String,type:{type:String,required:true},banner:String,price:{type:Number,required:true},available:{type:Boolean,default:true}},{timestamps:true}));
app.use(cors()); app.use(express.json());
app.get('/', async (req,res,next)=>{try{const products=await Product.find(); const categories=[...new Set(products.map(p=>p.type))]; res.json({products,categories});}catch(e){next(e)}});
app.get('/:id', async(req,res,next)=>{try{const p=await Product.findById(req.params.id); if(!p)return res.status(404).json({message:'Product not found'}); res.json(p);}catch(e){next(e)}});
app.post('/', async(req,res,next)=>{try{res.status(201).json(await Product.create(req.body));}catch(e){next(e)}});
app.use((e,req,res,next)=>res.status(500).json({message:e.message}));
async function start(){await mongoose.connect(DB_URL); console.log('Products DB connected'); app.listen(PORT,'0.0.0.0',()=>console.log(`Products listening on ${PORT}`));} start().catch(e=>{console.error(e);process.exit(1)});
